# Generated by Django 4.1.7 on 2023-04-24 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="create_at",
        ),
    ]
