# Generated by Django 4.1.7 on 2023-03-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="full_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
