# Generated by Django 4.1.7 on 2023-03-18 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0002_userdetail"),
        ("shortener", "0002_users_full_name"),
    ]

    operations = []
