# Generated by Django 4.1.7 on 2023-05-01 05:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0002_remove_organization_create_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shortenedurls",
            old_name="creat_via",
            new_name="create_via",
        ),
    ]
