# Generated by Django 4.1.7 on 2023-05-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0003_rename_creat_via_shortenedurls_create_via"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="shortenedurls",
            index=models.Index(
                fields=["prefix", "shortened_url"], name="shortener_s_prefix_bbcd1e_idx"
            ),
        ),
    ]
