# Generated by Django 4.1.7 on 2023-05-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0007_rename_shortened_url_trackingparams_shortened_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="telegram_username",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
